modLoader="kotlinforforge"
loaderVersion="[1,)"
license="LGPL 3.0"
showAsResourcePack=false

[[mods]]
modId="resourcify"
version="${version}"
displayName="Resourcify"
authors="DeDiamondPro"
description="In-game resource pack, data pack and shader browser"
logoFile="icon.png"

[[dependencies.resourcify]]
modId="kotlinforforge"
mandatory=true
versionRange="[1,)"
side="CLIENT"